---
title: "Calculate Distances Between States"
output: github_document
---

Now it's time to calculate the distances between states for each of the dataframes we created for each year of migration data.

```{r setup, message = FALSE, warning = FALSE, include = TRUE}
library(tidyverse)
library(here)
library(Imap)
#devtools::load_all()
```

## Load the data
```{r}
US_0910 <- read.csv(here("results", "data_cleaning_results", "clean", "US_0910.csv"))
US_1011 <- read.csv(here("results", "data_cleaning_results", "clean", "US_1011.csv"))
US_1112 <- read.csv(here("results", "data_cleaning_results", "clean", "US_1112.csv"))
US_1213 <- read.csv(here("results", "data_cleaning_results", "clean", "US_1213.csv"))
US_1314 <- read.csv(here("results", "data_cleaning_results", "clean", "US_1314.csv"))
US_1415 <- read.csv(here("results", "data_cleaning_results", "clean", "US_1415.csv"))
US_1516 <- read.csv(here("results", "data_cleaning_results", "clean", "US_1516.csv"))
US_1617 <- read.csv(here("results", "data_cleaning_results", "clean", "US_1617.csv"))
US_1718 <- read.csv(here("results", "data_cleaning_results", "clean", "US_1718.csv"))
states_fips <- read.csv(here("results", "data_cleaning_results", "states_fips.csv"))
```

## Combine all relevant informatioin into a single tibble
```{r}
join_with_location <- function(data) {
  joined <- left_join(data, states_fips %>% select(fips, latitude, longitude), by = c("origin_fips" = "fips"))
  joined <- rename(joined, origin_lat = latitude, origin_lon = longitude)
  joined <- left_join(joined, states_fips  %>% select(fips, latitude, longitude), by = c("dest_fips" = "fips"))
  joined <- rename(joined, dest_lat = latitude, dest_lon = longitude)
  joined
}

US_0910 <- join_with_location(US_0910)
US_1011 <- join_with_location(US_1011)
US_1112 <- join_with_location(US_1112)
US_1213 <- join_with_location(US_1213)
US_1314 <- join_with_location(US_1314)
US_1415 <- join_with_location(US_1415)
US_1516 <- join_with_location(US_1516)
US_1617 <- join_with_location(US_1617)
US_1718 <- join_with_location(US_1718)
```

## Add a column for distances between states
```{r}
# will be calculating geographic distance between the two states' major cities in miles
calculate_distances <- function(data, name) {
  data <- data %>%
    mutate(
      distance = pmap_dbl(list(origin_lon, origin_lat, dest_lon, dest_lat, units = "miles"), gdist)
    )
  filename <- here("results", "calculated_distances", name)
  write.csv(data, file = filename, row.names = FALSE)
}

# write each result out to a csv just in case
calculate_distances(US_0910, "US_0910_with_distances.csv")
calculate_distances(US_1011, "US_1011_with_distances.csv")
calculate_distances(US_1112, "US_1112_with_distances.csv")
calculate_distances(US_1213, "US_1213_with_distances.csv")
calculate_distances(US_1314, "US_1314_with_distances.csv")
calculate_distances(US_1415, "US_1415_with_distances.csv")
calculate_distances(US_1516, "US_1516_with_distances.csv")
calculate_distances(US_1617, "US_1617_with_distances.csv")
calculate_distances(US_1718, "US_1718_with_distances.csv")
```



